In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/LENOVO/Desktop/MCA/data science/weatherAUS.csv/weatherAUS.csv")

In [4]:
df.isnull()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
145456,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
145457,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
145458,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145459,False,False,False,True,False,True,True,True,True,False,...,False,False,False,False,False,False,False,False,False,True

In [5]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [7]:
df.isna()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145456,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145457,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145458,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
145459,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
dfc=df.dropna()

In [10]:
dfc.isna().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [11]:
dfc.drop_duplicates()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,True,True,True,True,False,...,False,False,False,False,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144326,False,False,True,False,True,True,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False
144925,False,False,True,False,False,True,True,True,True,False,...,False,False,False,False,True,False,False,False,False,True
144938,False,False,False,False,True,True,True,True,True,True,...,False,False,False,False,False,True,False,False,True,False
144949,False,False,False,False,False,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,True
145092,False,False,False,False,True,True,True,True,True,False,...,False,False,False,False,False,False,False,False,True,True

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [18]:
dfc.duplicated().sum()

np.int64(144439)

In [19]:
dfc.drop_duplicates()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,True,True,True,True,False,...,False,False,False,False,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144326,False,False,True,False,True,True,True,False,False,False,...,False,False,False,False,False,True,False,False,True,False
144925,False,False,True,False,False,True,True,True,True,False,...,False,False,False,False,True,False,False,False,False,True
144938,False,False,False,False,True,True,True,True,True,True,...,False,False,False,False,False,True,False,False,True,False
144949,False,False,False,False,False,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,True
145092,False,False,False,False,True,True,True,True,True,False,...,False,False,False,False,False,False,False,False,True,True

In [22]:
print(dfc.duplicated().sum())

144439

In [26]:
dfc.dtypes

Date             bool
Location         bool
MinTemp          bool
MaxTemp          bool
Rainfall         bool
Evaporation      bool
Sunshine         bool
WindGustDir      bool
WindGustSpeed    bool
WindDir9am       bool
WindDir3pm       bool
WindSpeed9am     bool
WindSpeed3pm     bool
Humidity9am      bool
Humidity3pm      bool
Pressure9am      bool
Pressure3pm      bool
Cloud9am         bool
Cloud3pm         bool
Temp9am          bool
Temp3pm          bool
RainToday        bool
RainTomorrow     bool
dtype: object

In [28]:
df["Date"] = pd.to_datetime(df["Date"],errors="coerce")

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           0 non-null       datetime64[ns]
 1   Location       145460 non-null  bool
 2   MinTemp        145460 non-null  bool
 3   MaxTemp        145460 non-null  bool
 4   Rainfall       145460 non-null  bool
 5   Evaporation    145460 non-null  bool
 6   Sunshine       145460 non-null  bool
 7   WindGustDir    145460 non-null  bool
 8   WindGustSpeed  145460 non-null  bool
 9   WindDir9am     145460 non-null  bool
 10  WindDir3pm     145460 non-null  bool
 11  WindSpeed9am   145460 non-null  bool
 12  WindSpeed3pm   145460 non-null  bool
 13  Humidity9am    145460 non-null  bool
 14  Humidity3pm    145460 non-null  bool
 15  Pressure9am    145460 non-null  bool
 16  Pressure3pm    145460 non-null  bool
 17  Cloud9am       145460 non-null  bool
 18  Cloud3pm       145460 non-null  bool
 19  Temp9am        145460 non-null  bool
 20  Temp3pm        145460 non-null  bool
 21  RainToday      145460 non-null  bool
 22  RainTomorrow   145460 non-null  bool
dtypes: bool(22), datetime64[ns](1)
memory usage: 4.2 MB

In [32]:
dfc.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False